module.exports = {
  'adding games to shopping cart': browser => {
    browser
      .url('http://localhost:8080/')
      .waitForElementVisible('#app', 5000)
      .assert.containsText('h1', 'Games')
      .assert.containsText('.cart h1', 'Carrinho')
      .assert.containsText('.cart .info', 'Até o momento,\no seu carrinho está vazio')
      .assert.elementCount('.game', 9)
      .assert.containsText('.game:first-of-type .title', 'Shards of Darkness')
      .assert.containsText('.game:first-of-type .price', 'R$ 71,94')
      .assert.hidden('.add-to-cart')
      .moveToElement('.game:first-of-type', 0, 0)
      .assert.hidden('.game:first-of-type .details')
      .assert.visible('.game:first-of-type .add-to-cart')
      .click('.game:nth-child(1)')
      .assert.containsText('.cart', 'Shards of Darkness')
      .assert.containsText('.cart .subtotal', 'R$ 71,94')
      .assert.containsText('.cart .shipping-cost', 'R$ 10,00')
      .assert.containsText('.cart .total', 'R$ 81,94')
      .click('.game:nth-child(2)')
      .assert.containsText('.cart', 'FIFA 18')
      .assert.containsText('.cart .subtotal', 'R$ 267,33')
      .assert.containsText('.cart .shipping-cost', 'R$ 0,00')
      .assert.containsText('.cart .total', 'R$ 267,33')
      .assert.hidden('.cart .remove')
      .moveToElement('.cart-item:first-of-type', 0, 0)
      .assert.visible('.cart-item:first-of-type .remove')
      .click('.cart-item:first-of-type')
      .click('.cart-item:first-of-type')
      .assert.containsText('.cart .info', 'Até o momento,\no seu carrinho está vazio')
      .end()
  }
}
